sudo: required

services:
  - docker

before_install:
  - docker build -t prasad/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true prasad/dockerreact npm run test

deploy:
  provider: elasticbeanstalk
  region:
  app:
  env:
  bucket_name:
  bucket_path:
  on:
    branch: master